version: '3.8'

services:
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: frikomicsDB
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mi-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
